# Generated by Django 3.0.5 on 2020-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='marvel')),
                ('desc', models.TextField()),
                ('weapon', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
